name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# 権限の設定を追加
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.2'
        channel: 'stable'
    
    - name: Install dependencies
      run: cd todo_app && flutter pub get
    
    - name: Analyze project source
      run: cd todo_app && flutter analyze
    
    - name: Run tests
      run: cd todo_app && flutter test
    
    - name: Build web
      run: cd todo_app && flutter build web --base-href "/todo-app/"
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./todo_app/build/web
        commit_message: "Deploy to GitHub Pages"
        force_orphan: true 